# Generated by Django 3.2.3 on 2021-07-13 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.CharField(max_length=1000, verbose_name='Содержание')),
                ('date', models.DateTimeField(verbose_name='Дата создания новости')),
                ('activity', models.BooleanField(verbose_name='Флаг активности')),
            ],
        ),
        migrations.CreateModel(
            name='Сomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('new', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_news', to='app_news.news', verbose_name='Новость')),
            ],
        ),
    ]
