# Generated by Django 3.2.3 on 2021-07-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='сomment',
            name='new',
        ),
        migrations.AddField(
            model_name='news',
            name='comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_comment', to='app_news.news', verbose_name='Комментарий'),
        ),
    ]
