# Generated by Django 3.2.3 on 2021-07-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20210716_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сomment',
            new_name='MyComment',
        ),
    ]
