# Generated by Django 3.2.3 on 2021-07-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_rename_сomment_mycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_comment', to='app_news.mycomment', verbose_name='Комментарий'),
        ),
    ]
