# Generated by Django 3.2.3 on 2021-07-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_alter_news_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comment',
        ),
        migrations.AddField(
            model_name='mycomment',
            name='news',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mycomment_news', to='app_news.news', verbose_name='Новость'),
        ),
    ]
