# Generated by Django 3.2.3 on 2021-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_auto_20210718_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='activity',
            field=models.BooleanField(choices=[('a', 'True'), ('n', 'False')], verbose_name='Флаг активности'),
        ),
    ]
