# Generated by Django 3.2.3 on 2021-07-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_alter_news_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('a', 'True'), ('n', 'False')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
