# Generated by Django 3.2.3 on 2021-08-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0010_news_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date'], 'verbose_name_plural': 'News'},
        ),
    ]
