# Generated by Django 3.2.3 on 2021-08-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0014_auto_20210809_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date'], 'permissions': (('can_publish', 'может публиковать'),), 'verbose_name': 'Новости', 'verbose_name_plural': 'News'},
        ),
    ]
