# Generated by Django 3.2.3 on 2021-08-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0015_alter_news_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='status',
        ),
        migrations.AddField(
            model_name='news',
            name='status_verifications',
            field=models.CharField(choices=[('a', 'True'), ('n', 'False')], default='n', max_length=1),
        ),
    ]
