# Generated by Django 3.2.3 on 2021-08-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0016_auto_20210822_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status_verifications',
            field=models.CharField(choices=[('a', 'True'), ('n', 'False')], max_length=1),
        ),
    ]
