# Generated by Django 3.2.3 on 2021-08-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0018_alter_news_status_verifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='activity',
            field=models.BooleanField(default=False, verbose_name='Флаг активности'),
        ),
    ]
