# Generated by Django 3.2.3 on 2021-08-20 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('verified_user', 'верифицированный пользователь'),)},
        ),
    ]
