# Generated by Django 3.2.3 on 2021-08-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='-', max_length=36),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='-', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_flag',
            field=models.BooleanField(default=False),
        ),
    ]
